<?php

declare(strict_types=1);

namespace App\Support\Extraction\Scoring;

use RuntimeException;

/**
 * One contract in the corpus, and the truth about it (#14 · #118).
 *
 * The ground truth is **hand-checked** and lives beside the document as JSON.
 * That is the whole design: a scorecard is only worth the truth it scores
 * against, and a truth generated by the same system being measured would make
 * every number a description of the model agreeing with itself.
 *
 * `tests/Corpus/LIMITATIONS.md` is required reading before quoting any figure
 * this produces. The corpus that ships is **synthetic**, so the numbers are
 * optimistic and #14 stays open until the same command has run against twenty
 * real contracts.
 */
final readonly class CorpusCase
{
    /**
     * @param  list<array{label: string, value: string, critical: bool}>  $dates
     * @param  list<string>  $traits
     * @param  list<string>  $provisions
     */
    private function __construct(
        public string $slug,
        public string $description,
        public string $text,
        public array $dates,
        public array $provisions,
        public array $traits,
    ) {}

    /**
     * Read every case in a directory, or one by slug.
     *
     * @return list<CorpusCase>
     */
    public static function load(string $directory, string $only = ''): array
    {
        if (! is_dir($directory)) {
            return [];
        }

        $cases = [];

        foreach (glob($directory.'/*.json') ?: [] as $path) {
            $slug = basename($path, '.json');

            // The manifest lives beside the cases and is not one of them.
            if ($slug === 'index') {
                continue;
            }

            if ($only !== '' && $slug !== $only) {
                continue;
            }

            $cases[] = self::read($path, $directory.'/'.$slug.'.txt');
        }

        usort($cases, static fn (self $a, self $b): int => strcmp($a->slug, $b->slug));

        return $cases;
    }

    private static function read(string $truthPath, string $textPath): self
    {
        if (! is_file($textPath)) {
            /*
             * Loudly, rather than scoring the cases that happen to be
             * complete. A corpus quietly missing a case reports a *better*
             * number than the real one, which is the direction that matters
             * here: PRD §12.3's zero tolerance is on misses, and a case that
             * was never run cannot miss anything.
             */
            throw new RuntimeException("Corpus case has ground truth but no document: {$textPath}");
        }

        /** @var array<string, mixed> $truth */
        $truth = json_decode((string) file_get_contents($truthPath), true, flags: JSON_THROW_ON_ERROR);

        $dates = [];

        foreach ($truth['dates'] ?? [] as $date) {
            if (! is_array($date) || ! is_string($date['label'] ?? null) || ! is_string($date['value'] ?? null)) {
                continue;
            }

            $dates[] = [
                'label' => $date['label'],
                'value' => $date['value'],
                'critical' => (bool) ($date['critical'] ?? false),
            ];
        }

        return new self(
            slug: basename($truthPath, '.json'),
            description: is_string($truth['description'] ?? null) ? $truth['description'] : '',
            text: (string) file_get_contents($textPath),
            dates: $dates,
            provisions: array_values(array_filter($truth['provisions'] ?? [], 'is_string')),
            traits: array_values(array_filter($truth['traits'] ?? [], 'is_string')),
        );
    }

    public function criticalCount(): int
    {
        return count(array_filter($this->dates, static fn (array $date): bool => $date['critical']));
    }
}
