<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * The workflow **definition** layer (PRD §4.4 F4.1, F4.3, F4.13, §6.2, §7.1,
 * §8.3 · IA §4 · issue #64).
 *
 * This is the half of the template/instance split that holds what a team
 * *intends* to happen. The runtime half — what is actually happening on 123
 * Main St — is the next migration, and `InstantiateWorkflow` is the one-way
 * door between them.
 *
 * PRD §7.1 calls the ambiguity this fixes the highest-impact correction in the
 * document:
 *
 * > `Workflow` means both "the standard procedure for selling a property" and
 * > "the live procedure running on 123 Main St." Same with `Stage`, and again
 * > with `Action` versus `Action Instance`.
 *
 * Every table here is a `*_template`, and nothing here is ever read at advance
 * time. If a query in `AdvanceWorkflow` ever touches one of these tables, the
 * snapshot guarantee (F4.5) has already been broken.
 *
 * ## `team_id` is nullable on the templates and it is load-bearing
 *
 * A null team is a **system** template — the seeded Listing and Buyer packs
 * every team starts with. A set team is one a team wrote or customised. Same
 * shape as `roles` and `deal_types`, and the same reason it cannot use
 * `productDefaults()`: that macro's `team_id` is deliberately NOT NULL,
 * because on a table holding customer data a null tenant is a leak. These
 * hold a team's *process*, and the shared ones hold nobody's.
 *
 * ## Owner is a role, never a person
 *
 * `owner_role` on stage and task templates is resolved to an actual human at
 * instantiation. A template naming Heather breaks the moment a team has a
 * different assistant — and templates ship between teams inside packs, where
 * naming a person is meaningless.
 */
return new class extends Migration
{
    public function up(): void
    {
        /*
         * F4.13. Templates ship as named, installable bundles — Listing,
         * Buyer, Rental Placement — which is Emily's framing and a natural
         * packaging and pricing unit. Her read on relative value: *"the
         * buyer's pack is way less than the listing. The listing is the most
         * important part."*
         *
         * Not team-scoped at all: a pack is a catalogue entry, the same for
         * everybody, and installing one copies templates rather than granting
         * a reference.
         */
        Schema::create('template_packs', function (Blueprint $table): void {
            $table->ulid('id')->primary();

            $table->string('name');
            $table->string('slug')->unique();
            $table->text('description')->nullable();

            $table->boolean('is_installed_by_default')->default(false);

            // Slice 7 prices these (#124). Held now because the pack is the
            // unit that gets priced, and retrofitting the column later means
            // backfilling every seeded pack.
            $table->string('price_tier')->nullable();

            $table->unsignedSmallInteger('sort_order')->default(0);

            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('workflow_templates', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('team_id')->nullable()->constrained('teams')->cascadeOnDelete();
            $table->foreignUlid('template_pack_id')->nullable()->constrained('template_packs')->nullOnDelete();

            $table->string('name');
            $table->text('description')->nullable();

            /*
             * Version is a label on the definition, not a mechanism.
             *
             * It answers "which version produced this deal" on a snapshot, and
             * it drives S41's in-use warning. It does not make instances
             * upgradeable — F4.5 says an in-flight deal is never rewritten,
             * and a version that could be *applied* would be exactly that.
             */
            $table->unsignedInteger('version')->default(1);
            $table->boolean('is_active')->default(true);

            $table->timestamps();
            $table->softDeletes();

            $table->index(['team_id', 'is_active']);
            $table->unique(['team_id', 'id']);
        });

        // Which templates a deal type may use. Many-to-many: a Buyer
        // Representation deal can offer both a purchase workflow and a
        // separate financing one (F4.7).
        Schema::create('deal_type_workflow_template', function (Blueprint $table): void {
            // No surrogate key: the pair *is* the identity, and a ULID here
            // would have to be generated by every `attach()` call that does not
            // go through a model.
            $table->foreignUlid('deal_type_id')->constrained('deal_types')->cascadeOnDelete();
            $table->foreignUlid('workflow_template_id')->constrained('workflow_templates')->cascadeOnDelete();

            $table->boolean('is_default')->default(false);

            $table->primary(['deal_type_id', 'workflow_template_id'], 'deal_type_workflow_template_primary');
        });

        Schema::create('stage_templates', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('workflow_template_id')->constrained('workflow_templates')->cascadeOnDelete();

            $table->string('name');
            $table->text('description')->nullable();
            $table->unsignedSmallInteger('sort_order');

            $table->unsignedSmallInteger('expected_duration_days')->nullable();
            $table->string('owner_role')->nullable();

            /*
             * IA §3, and the distinction the whole vocabulary rests on: **a
             * Stage is a period, a Milestone is a moment.** "Listing
             * Preparation" is a stage and not a milestone. "Property Listed"
             * is both.
             *
             * So a milestone costs one boolean and one string rather than a
             * table — and `client_facing_label` is what the client actually
             * reads. The internal stage name never reaches them (IA §9),
             * which matters because internal names say things like "Chase
             * lender".
             */
            $table->boolean('is_milestone')->default(false);
            $table->string('client_facing_label')->nullable();

            $table->timestamps();
            $table->softDeletes();

            $table->index(['workflow_template_id', 'sort_order']);
        });

        Schema::create('gate_templates', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('stage_template_id')->constrained('stage_templates')->cascadeOnDelete();

            // Resolved to an evaluator class by the registry (#67). An unknown
            // value throws there rather than defaulting to met.
            $table->string('gate_type');
            $table->string('label');
            $table->config('config');

            /*
             * Blocking or advisory, independently per gate. An advisory gate is
             * shown and explained and never refuses an advance — which is how
             * a team encodes "you probably want the survey back" without
             * making it a wall.
             */
            $table->boolean('is_blocking')->default(true);

            $table->unsignedSmallInteger('sort_order')->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->index(['stage_template_id', 'sort_order']);
        });

        Schema::create('task_templates', function (Blueprint $table): void {
            $table->ulid('id')->primary();
            $table->foreignUlid('stage_template_id')->constrained('stage_templates')->cascadeOnDelete();

            $table->string('title');
            $table->text('description')->nullable();
            $table->string('owner_role')->nullable();

            /*
             * Signed, and relative to the stage start. Negative means before
             * it — "order the survey three days before inspection opens" is a
             * real task in Emily's list, and a `due_offset_days` that could
             * only count forwards could not express it.
             */
            $table->smallInteger('due_offset_days')->nullable();

            // Feeds the `required_tasks_complete` gate (#67). A task is not
            // required by default: most are reminders, and a stage where every
            // task blocks is a stage nobody can leave.
            $table->boolean('is_required')->default(false);

            $table->unsignedSmallInteger('sort_order')->default(0);

            $table->timestamps();
            $table->softDeletes();

            $table->index(['stage_template_id', 'sort_order']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('task_templates');
        Schema::dropIfExists('gate_templates');
        Schema::dropIfExists('stage_templates');
        Schema::dropIfExists('deal_type_workflow_template');
        Schema::dropIfExists('workflow_templates');
        Schema::dropIfExists('template_packs');
    }
};
